# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  bitrix24-receiver:
    build:
      context: .
      target: final
      args:
        BITRIX_WEBHOOK_URL: ${BITRIX_WEBHOOK_URL}
        MESSAGE_TEMPLATE_PATH: ${MESSAGE_TEMPLATE_PATH}
        APP_PORT: ${APP_PORT}
    volumes:
      - ./bitrix24.message.tmpl:/etc/bitrix24.message.tmpl
    ports:
      - 127.0.0.1:4000:4000